+ isA('controller1','userAccount')
+ isA('supervisoryController1','userAccount')
+ isA('fw1','userAccount')
+ isA('fw2','userAccount')
+ isA('fw3','userAccount')
+ isA('icsHistorian','userAccount')
+ isA('icsDB','userAccount')
+ isA('corporateLaptop','userAccount')
+ isA('attacker','userAccount')

+ isA('controller1SU','superUserAccount')
+ isA('supervisoryController1SU','superUserAccount')
+ isA('fw1SU','superUserAccount')
+ isA('fw2SU','superUserAccount')
+ isA('fw3SU','superUserAccount')
+ isA('icsHistorianSU','superUserAccount')
+ isA('icsDBSU','superUserAccount')
+ isA('corporateLaptopSU','superUserAccount')
+ isA('attackerSU','superUserAccount')

+ residesOn('controller1','controller1SU')
+ residesOn('supervisoryController1','supervisoryController1SU')
+ residesOn('fw1','fw1SU')
+ residesOn('fw2','fw2SU')
+ residesOn('fw3','fw3SU')
+ residesOn('icsHistorian','icsHistorianSU')
+ residesOn('icsDB','icsDBSU')
+ residesOn('corporateLaptop','corporateLaptopSU')
+ residesOn('attacker','attackerSU')

+ compromised('attacker')

+ requires('control','controller1')
+ requires('control','supervisoryController1')
+ requires('icsManagement','icsHistorian')
+ requires('icsManagement','icsDB')
+ requires('corporateLAN','corporateLaptop')

+ requiresConnection('control','supervisoryController1','controller1')
+ requiresConnection('icsManagement','icsDB','icsHistorian')
+ requiresConnection('icsManagement','icsHistorian','supervisoryController1')
+ requiresConnection('icsManagement','icsHistorian','controller1')
+ requiresConnection('icsManagement','supervisoryController1','icsDB')
+ requiresConnection('corporateLAN','corporateLaptop','icsDB')
# The corporateLAN must be connected to the internet
+ requiresConnection('corporateLAN','attackerClient','corporateLaptop')

+ networkConnectsTo('attackerClient','corporateLaptop')

+ utility('control',10)
+ utility('icsManagement',5)
+ utility('corporateLAN',1)
